# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.3'
services:
  calvary-gateway-api:
    image: calvaryapigateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_R2DBC_URL=${LOCAL_R2DBC_URL}/calvaryApiGateway
      - SPRING_LIQUIBASE_URL=${LOCAL_PG_SERVER}/calvaryApiGateway
      - SPRING_ELASTICSEARCH_URIS=http://10.60.27.22:9301
      - SPRING_ELASTICSEARCH_REST_URIS=http://10.60.27.22:9301
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=http://10.60.27.22:9092
      - PG_DATABASE_PROD_PASSWORD=${PG_DATABASE_PROD_PASSWORD}
      - PG_DATABASE_PROD_USER=${PG_DATABASE_PROD_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - SANDBOX_INSTANCE_URLS=http://localhost:8388,http://10.60.27.22:8388,http://localhost:8385
    ports:
      - 8385:8385
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8385/management/health
      interval: 5s
      timeout: 5s
      retries: 40

  calvary-erp-client:
    image: ghacupha/calvary-client:0.0.1-SNAPSHOT
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      - SERVER_API_DOCKER_DEPLOY_HOST=http://calvary-gateway-api
      - SERVER_API_DOCKER_DEPLOY_PORT=8385 # TODO check application
      - SERVER_API_URL="http://calvary-gateway-api:8385/"
      - SERVER_API_URL_URL=http://calvary-gateway-api:8385
      - ERP_SYSTEM_DEV_PORT=8385
      - ERP_CLIENT_DEV_PORT=8388
    ports:
      - '8388:80'
      # - ${ERP_CLIENT_DEPLOYMENT_PROD_PORT}
